### PR TITLE
Bump up requirements for newer st2 and ubuntu versions, fixes issue #82

### PR DESCRIPTION
**Pull request by brainstorm**
The packs deploy successfully if vb RAM limits get bumped up.

### CODE REVIEW

**Comment by johandahlberg** [comment]
I would assume that the `/etc/st2/st2.conf` is under that location on Travis as well, looking at the log it looks like it is looking for the file in `/home/travis/build/arteria-project/arteria-packs/etc/st2/st2.conf`. Does that make sense? Quite annoying that there isn't an option to log in to the container on Travis though. We could consider switching to Circle CI, in the future, since they do allow you to log in via ssh to debug.

**Comment by brainstorm** [comment]
@johandahlberg I think that the main problem here is that the testsuite does not reproducibly execute well on different environments. This is why we are looking into migrating to docker-compose and using [st2's testing facilities](https://docs.stackstorm.com/development/pack_testing.html) within a docker container:

https://github.com/umccr/st2-arteria-docker

Kudos to @reisingerf for pushing this forward right now.

**Comment by brainstorm** [comment]
Here's the culprit, there's no `st2.conf` file in `$TRAVIS_BUILD_DIR` or anywhere since it's not fashionable anymore on st2 >2.4.x as @reisingerf mentioned a while ago:

skarmavbild 2017-10-25 kl 18 01 17

**Comment by johandahlberg** [comment]
Thanks for the help here folks. This should all have been taken care of in https://github.com/arteria-project/arteria-packs/pull/89 now.

**Pull request closed without merging**
