### PR TITLE
Runfolder search and modification to trace_runfolder.py

### PR DESCRIPTION
**Pull request by MatildaAslin**
### New script: runfolder_search.py
Enables arteria operators to search for runfolders using e.g. flowcell ID. Output contains runfolder state and biotank information. This script can be improved a lot, but this is a start. Props to @johandahlberg who supplied the backbone of the script. 

### Modified script: trace_runfolder.py
All actions matching "workflow" will now be listed for a certain trace tag. The reason for this is to include delivery workflows as well as archive workflows that have been started manually. The sync_workflow will also be listed, but personally I think that is OK.

### CODE REVIEW

**Comment by MatildaAslin** [comment]
@johandahlberg Yeah, that would be great. I looked into it a bit now and it looks like PyYAML  is not installed on arteria-master (for my user). This is a problem since we want arteria operators to be able to execute it without loading another environment. I guess this would somehow have to be updated in system-management and I have no clue where. I will not have time to investigate this before I go on vacation.

**Comment by johandahlberg** [comment]
@johanherman Do you think you could look at having `PyYAML` installed centrally on the arteria-master nodes?

**Comment by johanherman** [comment]
@johandahlberg @MatildaAslin `PyYAML` has now been manually installed on `mm-xart001` and `arteria-master` (and there is a PR for having it permanent in the Ansible playbook as well).

**Comment by MatildaAslin** [comment]
@johanherman Nice, thanks!

**Pull request merged**
